/* ########### */
/* # INCLUDE # */
/* ########### */


float *mpc123_get_x0();
float *mpc123_get_x(int k);
float *mpc123_get_u(int k);
float *mpc123_get_s(int k);
float *mpc123_get_p(int k);
float *mpc123_get_y(int k);
float *mpc123_get_nu(int k);
float *mpc123_get_Hxx(int k);
float *mpc123_get_Hxu(int k);
float *mpc123_get_Huu(int k);
float *mpc123_get_Hss(int k);
float *mpc123_get_f0x(int k);
float *mpc123_get_f0u(int k);
float *mpc123_get_f0s(int k);
float *mpc123_get_fx(int k);
float *mpc123_get_fu(int k);
float *mpc123_get_f(int k);
float *mpc123_get_gx(int k);
float *mpc123_get_gu(int k);
float *mpc123_get_g(int k);
float *mpc123_get_stat_time();
int *mpc123_get_stat_iter_ref();
int *mpc123_get_stat_num_factor();
int *mpc123_get_stat_num_solve();
int *mpc123_get_stat_num_iter_ref();
int *mpc123_get_iter();
int *mpc123_get_termcode();
int *mpc123_get_error_line();
int *mpc123_get_error_source();
float *mpc123_get_norm_d();
float *mpc123_get_dx(int k);
float *mpc123_get_du(int k);
float *mpc123_get_ds(int k);
float *mpc123_get_dp(int k);
float *mpc123_get_dy(int k);
float *mpc123_get_dnu(int k);
float *mpc123_get_rf0x(int k);
float *mpc123_get_rf0u(int k);
float *mpc123_get_rf0s(int k);
float *mpc123_get_rf(int k);
float *mpc123_get_rc(int k);
float *mpc123_get_rk(int k);
float *mpc123_get_rs(int k);
float *mpc123_get_rrf0x(int k);
float *mpc123_get_rrf0u(int k);
float *mpc123_get_rhsxs(int k);
float *mpc123_get_yny(int k);
float *mpc123_get_Gxx(int k);
float *mpc123_get_Gxu(int k);
float *mpc123_get_Guu(int k);
float *mpc123_get_Rux(int k);
float *mpc123_get_Vxx(int k);
float *mpc123_get_L(int k);
float *mpc123_get_Gx(int k);
float *mpc123_get_Gu(int k);
float *mpc123_get_Vx(int k);
float *mpc123_get_Ru(int k);
float *mpc123_get_debug_dgap();
float *mpc123_get_debug_phi();
float *mpc123_get_debug_minphi();
float *mpc123_get_debug_norm_r0();
float *mpc123_get_debug_norm_r();
float *mpc123_get_debug_norm_d();
float *mpc123_get_debug_mu0();
float *mpc123_get_debug_mu();
float *mpc123_get_debug_sigma();
float *mpc123_get_debug_mu_aff();
float *mpc123_get_debug_alpha_max();
float *mpc123_get_debug_mehrotra_alpha();
double *mpc123_get_time_max();
void mpc123_set_time_max(double tmax);

double mpc123_glqdocpip_timer_get();
void mpc123_glqdocpip_timer_start();
int mpc123_glqdocpip();

double mpc123_glqdocpip_performance_test_math_mv();
double mpc123_glqdocpip_performance_test_math_vtm();
double mpc123_glqdocpip_performance_test_math_mm();
double mpc123_glqdocpip_performance_test_math_mtm();
double mpc123_glqdocpip_performance_test_math_norm_inf();
double mpc123_glqdocpip_performance_test_math_vv_elediv();
double mpc123_glqdocpip_performance_test_math_mm_reorder();
double mpc123_glqdocpip_performance_test_structure_mult_fx0_v();
double mpc123_glqdocpip_performance_test_structure_mult_fx0T_v();
double mpc123_glqdocpip_performance_test_structure_mult_vT_fx0();
double mpc123_glqdocpip_performance_test_structure_mult_m_fx0();
double mpc123_glqdocpip_performance_test_structure_mult_fx0T_m();
double mpc123_glqdocpip_performance_test_affine();
double mpc123_glqdocpip_performance_test_reduced();
double mpc123_glqdocpip_performance_test_factor();
double mpc123_glqdocpip_performance_test_solve();
double mpc123_glqdocpip_performance_test_dereduce();
double mpc123_glqdocpip_performance_test_starting();
double mpc123_glqdocpip_performance_test_rhs_iter_ref();
double mpc123_glqdocpip_performance_test_iter_ref();
double mpc123_glqdocpip_performance_test_norm_d();
double mpc123_glqdocpip_performance_test_norm_r();
double mpc123_glqdocpip_performance_test_mu();
double mpc123_glqdocpip_performance_test_duality_gap();
double mpc123_glqdocpip_performance_test_calc_phi();
double mpc123_glqdocpip_performance_test_check_condiv();
double mpc123_glqdocpip_performance_test_max_stepsize();
double mpc123_glqdocpip_performance_test_mu_aff();
double mpc123_glqdocpip_performance_test_sigma();
double mpc123_glqdocpip_performance_test_corrector();
double mpc123_glqdocpip_performance_test_mehrotra_step();
double mpc123_glqdocpip_performance_test_step();
double mpc123_glqdocpip_performance_test_startup();
double mpc123_glqdocpip_performance_test_1_iteration();
double mpc123_glqdocpip_performance_test_1_iteration_iterref();
